# Copyright (c) 2021, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

{{- if and .Values.ldap.enabled .Values.ldap.credentials.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "amc.getsecretsname" (dict "root" . "type" "ldap") }}
  namespace: {{ .Values.namespace }}
  labels:
    weblogic.domainUID: {{ template "amc.domainname" . }}
type: Opaque
data:
  password: {{ .Values.ldap.credentials.password | b64enc | quote }}
{{- end }}
