# Copyright (c) 2021, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "amc.domainname" . }}-runtime-encryption-secret
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    weblogic.domainUID: {{ template "amc.domainname" . }}
type: Opaque
data:
  password: {{ (include "amc.runtimesecret" .) | b64enc | quote }}
