apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracledb.fullname" . }}
  labels:
    {{- include "oracledb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: tns
  selector:
    {{- include "oracledb.selectorLabels" . | nindent 4 }}
